
# Security Headers
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()" always;

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

add_header Referrer-Policy no-referrer;

# CSP
add_header Content-Security-Policy "default-src 'self'; connect-src 'self' $WS_SCHEME://$BACKEND_HOST:$BACKEND_PORT $BACKEND_HOST:$BACKEND_PORT; img-src 'self' data:; style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';" always; # Variables are replaced in Entrypoint
# sub_filter_once off; # Could be used later if needed
# sub_filter NONCE_PLACEHOLDER $request_id;