FROM node:lts AS react-build
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

# Install project dependencies
RUN npm install

COPY . ./

RUN npm run build -- --mode stage

# Build complete

FROM nginx:latest

COPY --from=react-build /app/dist/ /www/html

COPY ./nginx.conf /etc/nginx/templates/nginx.conf.template
COPY ./common-headers.conf /etc/nginx/templates/common-headers.conf.template

# Copied build to nginx image

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80
