FROM node:lts AS react-build
WORKDIR /app

ARG VITE_APP_VERSION=production
ENV VITE_APP_VERSION=${VITE_APP_VERSION}

COPY package.json ./
COPY package-lock.json ./

# Install project dependencies
RUN npm install

COPY . ./

RUN npm run build

# Build complete

FROM nginx:latest

COPY --from=react-build /app/dist/ /www/html

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./common-headers.conf /etc/nginx/includes/common-headers.conf
# COPY ./csp-header.conf /etc/nginx/includes/csp-header.conf

# Copied build to nginx image

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
