events {}

http {
    server {
        listen 80;
        listen [::]:80;

        root /www/html;

        server_tokens off;

        include mime.types;
        types {
            font/ttf ttf;
        }

        # Adds Content-type: charset=utf-8 to all response headers
        charset utf-8;
        charset_types *;

        include includes/common-headers.conf;

        location / {
            try_files $uri $uri/ /index.html =404;

            include includes/common-headers.conf;
            # include includes/csp-header.conf;

            add_header Cache-Control "no-cache, private" always;
        }

        location ~* \.(?:jpg|jpeg|gif|ico|svg|mp4|js)$ {
            include includes/common-headers.conf;
            # include includes/csp-header.conf;

            # access_log off;
            add_header Cache-Control "public, immutable, max-age=31536000" always;
        }

        location ~* \.(?:png|css|ttf)$ {
            include includes/common-headers.conf;

            # access_log off;
            add_header Cache-Control "public, immutable, max-age=31536000" always;
        }
    }
}