@backend_HostAddress = http://localhost:5023

GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json
Origin: http://localhost:5173

###


GET http://localhost:8080/weatherforecast
Accept: application/json
Origin: https://peerdrop.bjoernblessin.de