export const enum MessageType {
    CLIENT_TOKEN = "client-token",
    REMOTE_TOKEN = "remote-token",
    ERROR = "error",
    SUCCESS = "success",
    CLOSE_CONNECTION = "close-connection",
    ICE_CANDIDATE = "ice-candidate",
    SDP = "sdp",
    CONNECTION_REQUEST = "connection-request",
    CONNECTION_RESPONSE = "connection-response",
    ESTABLISH_CONNECTION = "establish-connection",
    CONNECTION_REQUEST_CANCELLED = "connection-request-cancelled",
    CONNECTION_STATE = "connection-state",
    DEVICE_HEARTBEAT = "device-heartbeat",
    DEVICE_CHANGED = "device-changed",
    QUICK_CONNECT = "quick-connect",
    LAN_PEERS = "lan-peers",
    LAN_PEERS_REQUEST = "lan-peers-request",
}
