export const enum MessageType {
    CLIENT_TOKEN = "client-token",
    REMOTE_TOKEN = "remote-token",
    ERROR = "error",
    SUCCESS = "success",
    CLOSE_CONNECTION = "close-connection",
    ICE_CANDIDATE = "ice-candidate",
    SDP = "sdp",
    TEST = "test",
    CONNECTION_REQUEST = "connection-request",
    CONNECTION_RESPONSE = "connection-response",
    ESTABLISH_CONNECTION = "establish-connection",
    CONNECTION_REQUEST_CANCELLED = "connection-request-cancelled",
    DEVICE_HEARTBEAT = "device-heartbeat",
    QUICK_CONNECT = "quick-connect",
}
