name: Docker Image Build & Push Frontend

on:
    workflow_call:
        inputs:
            tags:
                description: 'Comma-separated list of tags for the Docker image e.g., "1, 1.2, 1.2.3"'
                required: true
                type: string

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/peerdrop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Prepend image name to tags
              id: tagger
              run: |
                  TAGS=$(echo "${{ inputs.tags }}" | tr ',' '\n' | sed "s|^|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:|" | paste -sd "," -)
                  echo "tags=$TAGS" >> $GITHUB_OUTPUT

            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend/
                  file: ./frontend/Dockerfile.prod
                  push: true
                  tags: ${{ steps.tagger.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
