name: Docker Backend

on: workflow_call

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/peerdrop_backend

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/backend/
                  push: true
                  tags: ${{ inputs.tags }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
