name: Prettier

on:
    pull_request:
        branches:
            - main
    push:
        paths:
            - "frontend/**"

jobs:
    prettier:
        name: Run Prettier format check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Prettier
              run: |-
                  npx prettier --check "**/*.{ts,tsx,js,css,scss,hmtl}" --end-of-line lf
              working-directory: frontend
