on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - submitted

jobs:
  check_reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Add @bjoern621 as reviewer
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['bjoern621']
            });
